#!/bin/bash
#
# ping the other vlan-test-x box
#

cd ~bogo/vlaner

if [ $(hostname) = "vlan-test-a" ]; then
  HOST_FIELD=4
else
  HOST_FIELD=3
fi

while true; do
  
  MYIP=$(ip -o -4 addr show dev ens160 | awk '{split($4,a,"/"); print a[1]}')
  
  VLAN=$(grep "${MYIP}/" vlans.txt)
  ADDRESS=$(echo $VLAN | cut -d ' ' -f $HOST_FIELD | sed 's|/.*||')
  
  ping -c 1 $ADDRESS | head -2  | tail -1
  sleep 1

done

